-- =========================================================
-- 우리팀 일정 캘린더: Supabase 한 번에 설정하기
-- Supabase Dashboard > SQL Editor > New query > 전체 붙여넣기 > Run
-- 신규 프로젝트 기준입니다.
-- 담당 구분: 팀장 / 인사 / 감찰 / 교육 / 안전
-- =========================================================

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  color text not null check (color ~ '^#[0-9A-Fa-f]{6}$'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 담당은 5개 중 하나만 허용하고, 한 담당은 한 계정만 사용
alter table public.profiles drop constraint if exists profiles_role_allowed;
alter table public.profiles add constraint profiles_role_allowed
  check (display_name in ('팀장','인사','감찰','교육','안전'));
create unique index if not exists profiles_display_name_unique_idx on public.profiles(display_name);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 1 and 80),
  member_id uuid not null references public.profiles(id) on delete cascade,
  category text not null default '업무',
  start_date date not null,
  end_date date not null,
  all_day boolean not null default true,
  start_time time,
  end_time time,
  location text check (location is null or char_length(location) <= 80),
  notes text check (notes is null or char_length(notes) <= 500),
  color text not null check (color ~ '^#[0-9A-Fa-f]{6}$'),
  created_by uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint events_date_order check (end_date >= start_date),
  constraint events_time_required check (all_day = true or (start_time is not null and end_time is not null))
);

create index if not exists events_date_idx on public.events(start_date, end_date);
create index if not exists events_member_idx on public.events(member_id);

create or replace function public.set_updated_at()
returns trigger language plpgsql security invoker set search_path = '' as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at before update on public.profiles
for each row execute procedure public.set_updated_at();

drop trigger if exists set_events_updated_at on public.events;
create trigger set_events_updated_at before update on public.events
for each row execute procedure public.set_updated_at();

-- 회원가입 메타데이터의 담당명을 확인하여 담당별 고정 색상 지정
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  requested_role text;
  role_color text;
begin
  requested_role := new.raw_user_meta_data ->> 'display_name';
  role_color := case requested_role
    when '팀장' then '#E5484D'
    when '인사' then '#246BFD'
    when '감찰' then '#22A06B'
    when '교육' then '#F59E0B'
    when '안전' then '#7C3AED'
    else null
  end;

  if role_color is null then
    raise exception '허용되지 않은 담당 구분입니다.';
  end if;

  insert into public.profiles (id, display_name, color)
  values (new.id, requested_role, role_color);
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.events enable row level security;

drop policy if exists "Authenticated users can view team profiles" on public.profiles;
drop policy if exists "Users can insert own profile" on public.profiles;
drop policy if exists "Users can update own profile" on public.profiles;
drop policy if exists "Authenticated users can view events" on public.events;
drop policy if exists "Authenticated users can create events" on public.events;
drop policy if exists "Authenticated users can update events" on public.events;
drop policy if exists "Authenticated users can delete events" on public.events;

create policy "Authenticated users can view team profiles"
on public.profiles for select to authenticated using (true);

create policy "Users can insert own profile"
on public.profiles for insert to authenticated with check ((select auth.uid()) = id);

create policy "Users can update own profile"
on public.profiles for update to authenticated
using ((select auth.uid()) = id) with check ((select auth.uid()) = id);

-- 로그인한 5개 담당 계정은 모든 일정을 함께 보고/추가/수정/삭제할 수 있음
create policy "Authenticated users can view events"
on public.events for select to authenticated using (true);

create policy "Authenticated users can create events"
on public.events for insert to authenticated with check ((select auth.uid()) = created_by);

create policy "Authenticated users can update events"
on public.events for update to authenticated using (true) with check (true);

create policy "Authenticated users can delete events"
on public.events for delete to authenticated using (true);

revoke all on public.profiles from anon;
revoke all on public.events from anon;
grant select, insert, update on public.profiles to authenticated;
grant select, insert, update, delete on public.events to authenticated;
grant usage, select on all sequences in schema public to authenticated;

alter table public.events replica identity full;
alter table public.profiles replica identity full;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'events'
  ) then
    execute 'alter publication supabase_realtime add table public.events';
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'profiles'
  ) then
    execute 'alter publication supabase_realtime add table public.profiles';
  end if;
end $$;

-- 완료: Table Editor에서 profiles / events가 보이면 정상입니다.
